rtlabs-com/c-open

- src/osal/linux/osal.c
- src/osal/linux/osal_sys.h
- test/test_osal.cpp
Use (the linux-specific and fairly undocumented) SIGEV_THREAD_ID to
avoid creating a thread whenever a timer fires.
See #3.
> Rework linux timers

- src/osal/linux/osal.c
- src/osal/linux/osal_can.c
Set PRIO_INHERIT on all mutexes. Use clock_nanosleep and
CLOCK_MONOTONIC for usleep(). Set stacksize on threads.
> OSAL improvements

- CMakeLists.txt
Export the required include directories for use in a toplevel build which
includes this repo as a submodule/subdir and uses it like this:
add_subdirectory (lib/c-open)
target_link_libraries (slave PUBLIC canopen)
Remove the weird and now unnecessary coupling between the example
slave/master and the platform cmake files.
> Fix CMake to be able to use c-open as a submodule

- include/co_api.h
- src/co_sdo.h
Make SDO abort codes public as they are needed to implement an SDO
access function.
> Move SDO abort codes to public header

- src/osal/linux/osal_can.c
The syscall may be interrupted by a signal handler and return
prematurely. Simply retry when that happens.
This fixes the rx thread exiting after a debugger halt.
> osal/linux: Handle interrupted epoll_wait()

- src/co_od.c
Accessing an object through an lvalue of an incompatible type is
undefined behavior and even if it works in practice, the result will
differ depending on endianness. Use a temporary object of the correct
type instead.
> Pass a correctly typed pointer to co_access_fn

- src/co_pdo.c
- src/co_util.h
- test/test_pdo.cpp
Support padding using static datatypes as specified in CiA 301 chapter 7.4.7.1.
> Add support for PDO padding

- src/co_util.h
For some reason, CiA 417:3 specifies a COB-ID for PDO 261 which is
restricted by CiA 301 §7.3.5 for use as COB-IDs.
Relax the check to allow 0x180 in order to support these
applications.
> Allow COB-ID 0x180 to support CiA 417 profile

- src/co_main.c
- src/co_main.h
- src/co_pdo.c
- src/co_pdo.h
- test/mocks.cpp
- test/test_pdo.cpp
- test/test_util.h
Support sparse PDO numbering as used in e.g. the CiA417 spec by
maintaining the PDO number in the co_pdo_t state. Note that the number
of available PDOs is still expected to be small; all searches are
linear.
Fixes #12.
> Support sparse PDO numbering

- src/co_main.c
SYNC has the same function code as EMCY but it always broadcast.
> fix SYNC reception

- src/co_main.c
The reset callback was never stored from the config struct and therefore
not functional. Just add it in co_init().
> Make the NMT reset event callback work

- src/co_pdo.c
- test/mocks.cpp
- test/mocks.h
- test/test_pdo.cpp
If a received PDO is longer than the mapped objects, the device SHALL
consume the mapped part of the payload and MAY transmit an EMCY (CiA 301
7.5.2.36). Current code discards the data and sends an EMCY.
Only abort reception and send EMCY if the PDO length is shorter than the
mapped objects, as required. Process the frame normally and skip the EMCY
if the PDO is longer.
Fixes: rtlabs-com/c-open#21
> Accept too long PDOs

- src/co_pdo.c
The number_of_mappings argument to the validation function comes straight
from the 8-bit payload when writing to subindex 0 of the PDO mapping
objects and will, during the summing of the bitlengths, read outside the
mappings array if the payload is greater than MAX_PDO_ENTRIES.
> Fix index-out-of-bounds read when validating PDO mapping

- src/co_main.h
- src/co_pdo.c
- src/co_sync.c
If a TPDO communication parameter has the RTR bit set, meaning remote
transmission requests are not allowed for this PDO, the PDO transmission
will send an RTR frame instead of the data when it's triggered, due to a
missing mask on the COB-ID when sending the frame.
Also audit other cases of calling os_channel_send() without masking and
as a result, replace hard-coded mask constants in SYNC sending (one of
which was incorrect!) with the appropriate macro.
Include the extended-frame bit in the mask to support 29-bit frames if
these should be configured in any COB-ID; it makes little sense to
include all 29 ID bits in the mask if the extended-frame flag is left
out.
> Fix PDOs sending remote frames instead of actual data

- src/co_od.c
- test/test_od.cpp
If the current OD had an object with a larger data size than when the
objects were stored, only the smaller part of the uint64_t would be read
into, but the actual setting of the object would use the entire, partly
uninitialized, value.
Also, in the pointer case the size was not checked against the actual size
of the target object, which would cause memory corruption if the object had
been shrunk since the values were stored.
> Fix multiple data corruption in OD load

- include/co_api.h
- src/co_main.c
- src/co_main.h
- src/co_pdo.c
- src/co_pdo.h
- test/test_pdo.cpp
- test/test_util.h
The event used to trigger event-based PDOs is not necessarily the same for
all PDOs, however there is no API to trigger the transmission of anything
but all enabled PDOs.
Add a job type and supporting functions to trigger only PDOs which have a
specified object mapped.
Also add documentation and prototype that was missing for co_pdo_event().
> Make it possible to trigger only PDOs for a specific object

- include/co_api.h
- src/co_lss.c
- src/co_main.h
- src/co_od.c
- test/mocks.cpp
- test/mocks.h
- util/slave/slave.c
For a file-based storage backend, the implementation needs to be
unnecessarily complicated because it's unknown in the open() callback
whether the stack is going to read or write the file.
The only standard stdio file modes that supports both reading and writing
are "r+", "w+" and "a+". Of these, "w+" always truncates the file, deleting
the parameters when the stack wants to read them; "a+" only allows
appending, so existing stored parameters will not get updated. Only "r+"
technically works, but leaves garbage at the end of the file when writing
if the new data is shorter than the current file, so if it works or not
depends on the data format the stack uses internally.
Pass a new argument to the open() callback to let the implementation know
what the stack is going to do with the file. …
> Pass the read/write intent to the OD store open call

- src/co_pdo.c
- test/test_pdo.cpp
Don't allow transmitting any PDOs in other NMT states, even if the
application triggers them.
Fixes #40
> Only send PDOs in NMT Operational

- src/co_sdo_client.c
- src/co_sdo_server.c
- test/test_sdo_server.cpp
Any sufficiently large SDO transfer will time-out, because the time is
counted from the start of the transfer. Restart the timeout as long as
progress is made, for each transferred segment.
Also fill in the index and sub-index of the object in the abort frame
if the transfer times out locally, as per CiA 301.
Additionally, fix a flaw in the SegmentedTimeout test which used
synthetic timestamps but did not mock the system time, possibly causing
sporadic failure (or pass) if run at the wrong time.
Signed-off-by: Andreas Fritiofson <andreas.fritiofson@unjo.com>
Change-Id: Ic527f80cca1c3f72e26bebb0acd6d3b06800d546
> Fix SDO time-out on large segmented transfers

- src/co_main.c
- src/co_pdo.c
If a call to trigger a PDO event is done followed by a second job,
there's no guarantee that the main thread will have a chance to run
and process the PDO job to completion before the common job
description struct is overwritten by the next request.
Use the semaphore via the completion callback as for all other jobs.
> Synchronize PDO triggering with the c-open main thread

- include/co_api.h
- src/co_emcy.c
- src/co_main.h
- test/mocks.cpp
- test/mocks.h
- test/test_emcy.cpp
The automatic NMT transition to Pre-operational, or any other action
that has been configured in 1029h, is only required to happen on Bus-
off or Life guarding/Heartbeat time-out. Currently, all EMCYs that are
sent do trigger the error behaviour, even if the error is not a
"serious CANopen device failure". It even reverts back to pre-operational
when an error is cleared and EMCY 0x0000 is sent.
Turn off the error behaviour except for EMCY codes 0x8130 and 0x8140
which correspond to the mandatory events (although the Bus-off EMCY
actually means *recovery* from Bus-off, so the Error behavior will
happen much later than was probably intended).
Ref: #39
> Only trigger the Error behaviour on the mandatory events

- include/co_api.h
- src/co_emcy.c
- src/co_main.c
- src/co_main.h
- src/co_nmt.c
- src/co_od.c
- src/co_pdo.c
- src/co_sync.c
- test/mocks.cpp
- test/mocks.h
- util/slave/slave.c
It's currently impossible to reach the network handle from callbacks
that are called during co_init(), because even if the cb_arg is already
set up to point to a global object that is going to hold the network
handle, co_init() must return the handle before it can be stored there.
Add a function to retrieve the cb_arg opaque argument from the network
handle when needed. This is also useful to reach application specific
context in the object access functions.
Also add a function to get the node ID, which may differ from the default
because of LSS.
> Pass the network handle to callback functions instead of cb_arg

- include/co_api.h
- src/co_nmt.c
- test/test_nmt.cpp
Treat each sub-state as a separate step in the FSM processing, to expose
the sub-states to the application NMT callback, which may need to do
different things depending on whether the application or only the
communication is reset.
The previous STATE_INIT in an NMT callback now corresponds to
STATE_INIT_COMM, so add an alias to keep the behaviour of existing
callbacks.
Move the reset callback to the NMT command reception to avoid having to
disable it during power-on initialisation.
> Split NMT Initialisation state into its three sub-states

- include/co_api.h
- src/co_emcy.c
- src/co_main.c
- src/co_main.h
- test/test_emcy.cpp
A workaround for CAN drivers which doesn't take care of bus-off recovery themselves. Since there is no API to go bus on again from the application, let the stack attempt recovery after a configurable delay (like the restart-ms argument to SocketCAN drivers).
Also perform any actions that should be done at bus-off (error behavior and application notification) at the actual bus-off event, instead of when/if it recovers. For the application notification, reuse the EMCY callback with the 0x8140 code.
> Bus off recovery

- include/co_api.h
- src/co_heartbeat.c
- src/co_main.c
- test/test_heartbeat.cpp
The co_node_next function should not return true for nodes that have
failed the heartbeat protocol.
> Indicate hearbeat protocol state in node map

- src/co_pdo.c
- test/test_od.cpp
It should not be possible to update enabled PDO:s, except if in
STATE_INIT when the dictionary is restored.
Fix #51.
> Fix restoring of PDO config

- src/co_emcy.c
- src/co_heartbeat.c
- src/co_heartbeat.h
- src/co_main.c
- src/co_main.h
- src/co_node_guard.c
- src/co_node_guard.h
- src/co_pdo.c
- src/co_pdo.h
- src/co_sdo.h
- src/co_sdo_client.c
- src/co_sdo_server.c
- src/co_sync.c
- src/co_sync.h
- src/co_util.h
- test/mocks.cpp
- test/mocks.h
- test/test_emcy.cpp
- test/test_heartbeat.cpp
- test/test_node_guard.cpp
- test/test_pdo.cpp
- test/test_sdo_server.cpp
- test/test_util.h
Switch to using ticks from OSAL instead of calculating in time. The time function in OSAL does not always wrap on uint32_t boundaries, which causes problems with execution.
This depends on: https://github.com/rtlabs-com/osal/pull/19
> Switch to using ticks instead of time in osal

- src/ports/rt-kernel/coal_can.c
The data provided from rt-kernel can include dlc of greater than 8 (up to 15), which will lead to an out of bounds read and write.
Fixes #58
> Limit dlc to 8 in can reception
